<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:08:39.
 */
class setoresModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var setoresModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new setoresModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers setoresModel::SendMessage
     * @todo   Implement testSendMessage().
     */
    public function testSendMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers setoresModel::getAssuntos
     * @todo   Implement testGetAssuntos().
     */
    public function testGetAssuntos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers setoresModel::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers setoresModel::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
